# SPDX-FileCopyrightText: 2020 microG Team
# SPDX-License-Identifier: CC0-1.0

name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          cache: gradle
      - run: ./gradlew --no-daemon build
        env:
          TERM: dumb
